//Entity
export const GET_ENTITIES = 'GET_ENTITIES'
export const GET_ENTITY = 'GET_ENTITY'
export const CREATE_ENTITY = 'CREATE_ENTITY'
export const UPDATE_ENTITY = 'UPDATE_ENTITY'

//Jobsite
export const UPDATE_JOBSITE_FORM = 'UPDATE_JOBSITE_FORM'

//Specification
export const ACKNOWLEDGE_SPECIFICATION = 'ACKNOWLEDGE_SPECIFICATION'

//User
export const LOGIN_USER = 'LOGIN_USER'
export const LOGOUT_USER = 'LOGOUT_USER'
export const USER_REFRESH_NEEEDED = 'USER_REFRESH_NEEEDED'
export const UPDATE_LOGIN_FORM = 'UPDATE_LOGIN_FORM'