//Company
export const POPULATE_COMPANY_USER_OPTIONS = 'POPULATE_COMPANY_USER_OPTIONS'

//Entity
export const GET_ENTITIES = 'GET_ENTITIES'
export const GET_ENTITY = 'GET_ENTITY'
export const CREATE_ENTITY = 'CREATE_ENTITY'
export const UPDATE_ENTITY = 'UPDATE_ENTITY'

//Jobsite
export const CREATE_JOBSITE = 'CREATE_JOBSITE'
export const CREATE_JOBSITE_USER = 'CREATE_JOBSITE_USER'
export const DELETE_SPECIFICATION = 'DELETE_SPECIFICATION'
export const GET_COMPANY_JOBSITES = 'GET_COMPANY_JOBSITES'
export const GET_JOBSITE = 'GET_JOBSITE'
export const HIDE_JOBSITE_FORM = 'HIDE_JOBSITE_FORM'
export const HIDE_JOBSITE_USER_FORM = 'HIDE_JOBSITE_USER_FORM'
export const REFRESH_SPECIFICATIONS_LIST = 'REFRESH_SPECIFICATIONS_LIST'
export const RESET_JOBSITE_STATE = 'RESET_JOBSITE_STATE'
export const SHOW_JOBSITE_FORM = 'SHOW_JOBSITE_FORM'
export const SHOW_JOBSITE_USER_FORM = 'SHOW_JOBSITE_USER_FORM'
export const SPECIFICATIONS_NEED_REFRESH = 'SPECIFICATIONS_NEED_REFRESH'
export const UPDATE_JOBSITE_FORM = 'UPDATE_JOBSITE_FORM'

//SignUp
export const POPULATE_COMPANY_OPTIONS = 'POPULATE_COMPANY_OPTIONS'
export const RESET_SIGNUP_FORM = 'RESET_SIGNUP_FORM'
export const UPDATE_SIGNUP_FORM = 'UPDATE_SIGNUP_FORM'

//Specification
export const ACKNOWLEDGE_SPECIFICATION = 'ACKNOWLEDGE_SPECIFICATION'
export const CREATE_SPECIFICATION = 'CREATE_SPECIFICATION'
export const HIDE_SPECIFICATION_FORM = 'HIDE_SPECIFICATION_FORM'
export const SHOW_SPECIFICATION_FORM = 'SHOW_SPECIFICATION_FORM'

//User
export const LOGIN_USER = 'LOGIN_USER'
export const LOGOUT_USER = 'LOGOUT_USER'
export const USER_REFRESH_NEEEDED = 'USER_REFRESH_NEEEDED'
export const UPDATE_LOGIN_FORM = 'UPDATE_LOGIN_FORM'