//Entity
export const GET_ENTITIES = 'GET_ENTITIES'
export const GET_ENTITY = 'GET_ENTITY'
export const CREATE_ENTITY = 'CREATE_ENTITY'
export const UPDATE_ENTITY = 'UPDATE_ENTITY'

//Jobsite
export const CREATE_JOBSITE = 'CREATE_JOBSITE'
export const GET_COMPANY_JOBSITES = 'GET_COMPANY_JOBSITES'
export const GET_JOBSITE = 'GET_JOBSITE'
export const HIDE_JOBSITE_FORM = 'HIDE_JOBSITE_FORM'
export const RESET_JOBSITE_STATE = 'RESET_JOBSITE_STATE'
export const SHOW_JOBSITE_FORM = 'SHOW_JOBSITE_FORM'
export const UPDATE_JOBSITE_FORM = 'UPDATE_JOBSITE_FORM'

//Specification
export const ACKNOWLEDGE_SPECIFICATION = 'ACKNOWLEDGE_SPECIFICATION'
export const CREATE_SPECIFICATION = 'CREATE_SPECIFICATION'
export const HIDE_SPECIFICATION_FORM = 'HIDE_SPECIFICATION_FORM'
export const SHOW_SPECIFICATION_FORM = 'SHOW_SPECIFICATION_FORM'

//User
export const LOGIN_USER = 'LOGIN_USER'
export const LOGOUT_USER = 'LOGOUT_USER'
export const USER_REFRESH_NEEEDED = 'USER_REFRESH_NEEEDED'
export const UPDATE_LOGIN_FORM = 'UPDATE_LOGIN_FORM'